FROM python:3.11-slim
WORKDIR /app
COPY ingestion/ ingestion/
COPY data/ data/
COPY requirements.txt .
RUN apt update && apt install -y poppler-utils
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python3", "ingestion/pathway_ingestor.py"]

